# .github/workflows/deploy-github-pages.yaml

# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main' # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4

      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: cd packages/design-system
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: cd packages/design-system && pnpm install # default: npm ci
          build_command: cd packages/design-system && build # default: npm run build-storybook
          path: ./packages/design-system/storybook-static # default: dist/storybook
          checkout: false # default: true